### ISSUE TITLE
Clear the screen when pressing the trigger

### ISSUE THREAD

**Issue by EricGlaenzer** [SocketMobile/over-21-ios#18]
What ever previous scanning result is displayed on the screen, when the user press the trigger button then we should clear the screen to what it was when the scanner first connects.

**Comment by EricGlaenzer** [comment]
Meaning that if the result of the previous scan is on the screen, it should be cleared, and if an error message is on the screen it should go away.

**Comment by Chrishon-Socket** [comment]
This was addressed in pull request #26
