### ISSUE TITLE
Wrong barcode error message

### ISSUE THREAD

**Issue by EricGlaenzer** [SocketMobile/over-21-ios#21]
We should invite the user to toggle the Code 128 to disable state if the decoded data we received came from a code 128 data source.
The text could say: "Wrong barcode. You can toggle Code 128 to avoid this message."

If it's not a Code 128, then we can just display: "Wrong barcode. Try again."

**Comment by EricGlaenzer** [comment]
The text should simply say: "Wrong barcode. Please try again."

**Comment by Chrishon-Socket** [comment]
Is there a reason that Code128 will offer the option to toggle it and any other symbology (aside from PDF417) will automatically become disabled without any toggle option?

**Comment by EricGlaenzer** [comment]
no, it came from the fact that Code 128 is at least on the NY driver license. We don't offer anymore the option to toggle the Code 128 symbology. The "wrong" symbologies would be turned off automatically and store into the user default settings. The user could then restore the scanner original settings.

**Comment by Chrishon-Socket** [comment]
Okay got it.
