### ISSUE TITLE
Make sure the data we received are what we expect

### ISSUE THREAD

**Issue by EricGlaenzer** [SocketMobile/over-21-ios#7]
One some driver license there might have more than one barcode.
If the barcode scanned is not what is expected we should display a message to tell the user to scan the other barcode. 
We could also disable the barcode (in one of the driver license it's a Code 128), but we might need a way to reactivate this barcode as we often use Code 128 to configure the scanner.

**Comment by LenOttSocketMobile** [comment]
Instead of disabling, why don't we just check the symbology ID and ignore anything not PDF417

**Comment by EricGlaenzer** [comment]
I think we should give some kind of feedback to the user though... Like it's not obvious when you scan the scanner beeps, but you have nothing on the screen...
