### ISSUE TITLE
Trigger buttons definition

### ISSUE THREAD

**Issue by EricGlaenzer** [SocketMobile/over-21-ios#8]
I think it's best to use their "pre-defined" value instead of using hardcoded value.
` if buttonsState == .middle ` instead of ` if buttonsState.rawValue == TRIGGER_BUTTON_PRESSED`

I will add a state for none in Capture SDK

**Comment by Chrishon-Socket** [comment]
> Using the pre-defined value `.middle` would allow me to observe that the middle button has been pressed. But how would I determine whether it was released? I used the `TRIGGER_BUTTON_RELEASED` to update the UI

Nevermind, I thought the `else` block might accidentally target the other button states but I see that we are only observing `scanButtonPress` and `scanButtonRelease`. I tested just now

**Comment by EricGlaenzer** [comment]
The next version of the SDK will have a `.None` when no button is pressed.
